### PR TITLE
button.html

### PR DESCRIPTION
**Pull request by imdhanish**
I have created three types of button
1.Color oriented
2.Size oriented
3.Border radius
just click the button.html to see code

### CODE REVIEW

**Comment by imdhanish** [comment]
done

**Comment by lazycipher** [comment]
you need to create a directory with your username... then put button code in index.html

**Comment by lazycipher** [comment]
@imdhanish  I'll mark this PR as *Invalid* if you'll not correct things asap!

**Comment by imdhanish** [comment]
wait man

**Comment by imdhanish** [comment]
done

**Comment by lazycipher** [comment]
@imdhanish  Delete button.html and then create PR

**Pull request merged**
